### ISSUE TITLE
Get same for Android

### ISSUE THREAD

**Issue by ivanjeremic** [RVxLab/tailwind-plugin-ios-full-height#1]
Hello, thanks for this plugin works great! Now a question I have is how can I have the same effect on Android devices? Adding 100vh for android phones doesn't fix the issue.

I have a layout which is a 100vh grid, I used your plugin to make the layout on IOS 100vh which works

`<div className="grid grid-cols-3 grid-rows-lyro h-screen-ios min-h-screen-ios">`

but how can I add on Android the same effect?

**Comment by RVxLab** [comment]
I'm really glad this works well for you.

`h-screen-ios` and `min-h-screen-ios` are specifically meant for WebKit on touch devices. As far as I know you can just add `min-h-screen` or `h-screen` for Android.

I don't use Android however so I wouldn't be able to say for sure.
